### PR TITLE
Ignore csv and session files by git

### PR DESCRIPTION
**Pull request by wopfel**
Using these 2 new entries, the database and the session files are ignored.

Thank you for this script! I'm using it since a few days and it's awesome 😃 

By the way, 'git status' shows the modified config.php. That's because it is already captured in the git archive.
To get the file ignored by git, it could be renamed to 'config.php.sample'. What do you think about it?

Kind regards,
Bernd

### CODE REVIEW

**Comment by db-EV** [comment]
I'm not using git on desktop so I have no idea how things exactly working there.
What's happening right now with the config.php if 1) the user change it and 2) if it be changed on GitHub?

/Daniel

**Comment by wopfel** [comment]
Hi Daniel,
Thanks for your response.

I've cloned your repo and modified config.php. When doing a "git status" locally on my server, it shows config.php as changed. The config file would be included in a "git add .".

```
% LANG=C git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   config.php
```

If the config.php file would be changed in repo, it could result in a merge conflict when the user pulls the repo again. 

Kind regards,
Bernd

**Comment by db-EV** [comment]
But isn't it what I want? The config.php is only changing when new functions are implemented that need configuration. I think it's ok to get a merge conflict in this case, otherwise the user never reacts over changes on this file.

/Daniel

**Comment by wopfel** [comment]
That‘s an interesting point and I‘m totally fine with that 😊 

(There are alternatives such as showing deprecated options, managing changed options, refusing older options. But I think that‘s a bit more complicated.)

Thanks for merging 😃 

Kind regards,
Bernd

**Pull request merged**
